### ISSUE TITLE
Is there a 'flat' (distorted) way to view the sky images?

### ISSUE THREAD

**Issue by SultanOrazbayev** [cds-astro/ipyaladin#56]
Apologies in advance if I don't use the right terminology!

When using `ipyaladin` with grid, I can see that the grid lines vary depending on the location in the sky (RA/DEC). I understand this is the accurate representation of the celestial sphere, but for specific viz purposes I am interested in maintaining consistent grid size (which would require distorting the raster images). Does `ipyaladin` have such functionality?

**Comment by ManonMarchand** [comment]
Hello!

I'm not sure I get what you want, but maybe one of the available projections fits your need? (I'm thinking AIT?)

![image](https://github.com/cds-astro/ipyaladin/assets/16650466/611d600f-e9a3-422d-8cea-719e68cded0b)

Otherwise, I'm happy to here more :)

**Comment by SultanOrazbayev** [comment]
Thank you for the quick response! 

I iterated over all the projections, but when I zoom out, they all have non-rectangular grids. The best analogy I have is the Mercator projection for GIS applications (which shows the rectangular grids by distorting the land shapes).

Given the rasterized images, I guess this will require distorting the pixel images... not sure if this is feasible via Aladin.

**Comment by SultanOrazbayev** [comment]
From the Earth maps analogy, I am looking for a cylindrical projection, when I iterate over the projections in the upper right hand side I always get curved grids:
<img width="717" alt="Screenshot 2023-05-23 at 13 59 42" src="https://github.com/cds-astro/ipyaladin/assets/20208402/85afb103-0ef8-492f-a71c-611b16fce7a8">

**Comment by SultanOrazbayev** [comment]
Apologies for the multiple posts, but this image is basically what I am interested in (with the actual image/rasters over the grid): 
![](https://in-the-sky.org/data/constellations_map_equ11011.png)

**Comment by bmatthieu3** [comment]
Hi @SultanOrazbayev,

Thanks for using ipyaladin. From what I understand, you would like being able to move in a fixed projection centered around (ra, dec) = (0, 0). A little bit like what does openStreetMap when you move. That way you will have a "fixed" grid but depending on where you go, region will have more or less distortions (e.g. delta = 90, alpha = X is very distored).

I can imagine we can have an option to snap the projection to be centered around a specific sky location in the future. This is an option that makes sense for mercator/car types of projection but not for all (I think it does not have sense to propose that for non allsky projections like tan/sin because we will never have a chance to see all the sky).

This sure is a good feature to have but as it involves a major code extension and maybe a little bit of refactoring, unfortunately (even if it is very fun to implement I suppose) this is not something that may be considered in a near future. Of course, if more users consider it as nice to have for their use cases then the priority may be reevaluated. Still, I will open an issue for that on Aladin Lite.

**Comment by SultanOrazbayev** [comment]
Thank you for the quick follow-up, @bmatthieu3 ! I wasn't sure if I was missing some easy functionality, but it does sound like quite a bit of additional coding, so I will close this issue if it's OK.
